name: Deploy to VPS

env: 
    HOST: ${{ secrets.HOST }}
    USER: ${{ secrets.USER }}
    SSH_KEY: ${{ secrets.SSH_KEY }}
    
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Init .env files
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > apps/frontend/.env
          echo "${{ secrets.BACKEND_ENV }}" > apps/backend/.env

      - name: Run ESlint
        run: yarn turbo run lint

      - name: Build application
        run: yarn turbo run build

      - name: Deploy to VPS
        if: success()

        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $USER@$HOST << "EOF"
            cd cinema-web-kpi/
            git pull origin main
     
            turbo build
            pm2 restart cinema-project

          EOF
          rm ssh_key
