name: Deploy to VPS

env: 
    HOST: ${{ secrets.HOST }}
    USER: ${{ secrets.USER }}
    SSH_KEY: ${{ secrets.SSH_KEY }}
    
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Init .env files
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > apps/frontend/.env
          echo "${{ secrets.BACKEND_ENV }}" > apps/backend/.env

      - name: Install dependencies
        run: |
          yarn cache clean
          yarn install
          yarn turbo run lint
          yarn turbo run build

      - name: Deploy to VPS
        if: success()

        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $USER@$HOST << "EOF"
            cd /var/www/cinema-web-kpi/
            git pull origin main
          
            if git diff --name-only HEAD^ HEAD | grep -q "schema.prisma"; then
              echo "Changes detected in Prisma schema. Running migrations..."
              cd /var/www/cinema-web-kpi/apps/backend
          
              npx prisma migrate deploy
          
              cd /var/www/cinema-web-kpi/
            fi
          
            if git diff --name-only HEAD^ HEAD | grep -q "package.json"; then
                echo "Changes detected in Package json. Running installation..."
                cd /var/www/cinema-web-kpi/
                yarn install
            fi
            
            turbo build
            pm2 restart cinema-project

          EOF
          rm ssh_key
